### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by KodrAus** [elastic-rs/elastic-reqwest#42]
Once there's an async client for `reqwest` we should offer async versions of the traits in this crate.

It might need a little rework in a few places:

- `ElasticClient` needs an async variant that returns a future
- `IntoBody` needs an async variant
- We'll probably need to introduce a proper error type so the response future can be chained with `into_response`

The specific details depend on what the async API for reqwest ends up looking like.

**Comment by stephanbuys** [comment]
@KodrAus, I'm also looking at futures at the moment, if I can help with please let me know.

**Comment by KodrAus** [comment]
@stephanbuys Any input would be great :)

I'll keep an eye on https://github.com/seanmonstar/reqwest/issues/149. I think if we mostly mimic what it does we should be right.

**Comment by KodrAus** [comment]
For https://github.com/elastic-rs/elastic/issues/167, I think we should remove the blanket implementation on `IntoBody`, and add them manually. That way we can keep the body types consistent between the `sync::IntoBody` and `async::IntoBody` types.

I still haven't thought of a good way to slice the API up. `reqwest` is using modules, but that's mostly to keep it private for stabilisation. There should only be a few extra bits, so it might not be worth pulling things into modules:

```rust
trait SyncIntoBody {}
trait AsyncIntoBody {}

trait SyncElasticClient {}
trait AsyncElasticClient {}
```
